name: Publish to npm
permissions:
    contents: read # Required for actions/checkout to read the repository
    id-token: write # Optional, for OIDC-based authentication if using cloud services

on:
  push:
    tags:
      - 'v*'  # Triggers only for tags that start with 'v' (e.g., v1.0, v1.1.0)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        redis:
            image: redis:latest
            ports:
                - 6379:6379
            options: >-
                --health-cmd "redis-cli ping || exit 1"
                --health-interval 5s
                --health-timeout 5s
                --health-retries 5

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests for all apps
        run: cd test/e2e_apps/app_for_password_in_separate_table && npm i
      - run: cd test/e2e_apps/app_for_password_in_users_table && npm i
      - run: cd test/e2e_apps/app_with_auth_and_sessions_implemented && npm i
      - run: cd test/e2e_apps/app_for_magic_links && npm i
      - run: cd test/e2e_apps/app_for_mfa_sms_code && npm i
      - run: cd test/e2e_apps/app_for_mfa_totp && npm i
      - run: cd test/e2e_apps/app_for_forgotten_password_and_reset_password_flows && npm i
      - run: npm run cover

      - name: Build project
        run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # or the node version you're using
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Lint package
        run: npm run lint:package

      - name: Publish to npm
        run: npm publish  --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}